### ISSUE TITLE
ログインができない

### ISSUE THREAD

**Issue by syuilo** [Frost-Dev/Frost#18]
* PUT https://frost-social.ml/session で 400 が返ってきている模様
* レスポンスにエラーメッセージなどは含まれていない
* リクエストペイロードは`password`と`screenName`と`_csrf`が送られているようである

Browser: Chrome 63.0.3239.132

**Comment by marihachi** [comment]
つらそう それに再現性はありそうですか？

**Comment by marihachi** [comment]
手順があれば教えて欲しい

**Comment by marihachi** [comment]
エラー表示に関して修正を行ったので、これで原因に近づけるかもしれない

**Comment by syuilo** [comment]
パスワードが間違ってた....
どうやら登録時にパスワードをtypoしていたようで最早ログイン不能になった

**Comment by marihachi** [comment]
なるほどね
アカウントを消しておいても大丈夫？

再入力の項目が必要かもね
