### ISSUE TITLE
ポストの本文に独自スタイルを設定できるように

### ISSUE THREAD

**Issue by marihachi** [Frost-Dev/Frost#3]

**Comment by otofune** [comment]
特定HTMLタグのみ許可するかMarkdown記法などに対応するかどちらだろうか

**Comment by marihachi** [comment]
@otofune 
よくwikiとかで使うような擬似的な関数機能を用意してスタイルとかいじれるようにしようかなって思った

**Comment by ToMeWelcome** [comment]
個人的にはMarkdownの方が実装が楽だと思われ

**Comment by marihachi** [comment]
色とかはつけれなくていいかな
クライアントでの実装が複雑に必然的に難しくなるし

**Comment by marihachi** [comment]
markdownにします
