### ISSUE TITLE
DevContainerを導入して開発者間の環境を揃える

### ISSUE THREAD

**Issue by marihachi** [Frost-Dev/Frost#36]

**Comment by ThinaticSystem** [comment]
# お得情報

**Comment by ThinaticSystem** [comment]
[`pnpm fetch`](https://pnpm.io/ja/cli/fetch)使うと`packege-lock.json`だけ使われるからなるべくキャッシュ使ってくれるっぽい

**Comment by ThinaticSystem** [comment]
`package-lock.json`ないって言われて発狂してたら`pnpm-lock.yaml`だった（まいチク）

**Comment by ThinaticSystem** [comment]
Docker Engine破壊してワロタなの
```
ts@pecchin:~/dev/frost$ sudo service docker restart
/etc/init.d/docker: 62: ulimit: error setting limit (Invalid argument)
```

**Comment by ThinaticSystem** [comment]
えなんか直ったこわいこわいこわいこわい

**Comment by marihachi** [comment]
そういうときもある（？）

**Comment by ThinaticSystem** [comment]
とりあえずできた

**Comment by ThinaticSystem** [comment]
## 取扱説明書
https://github.com/Frost-Dev/Frost/commit/48ce88693d9c8cd22d8476048ebcf509905c93d7
