### ISSUE TITLE
開発環境でDBが使えるように

### ISSUE THREAD

**Issue by marihachi** [Frost-Dev/Frost#50]

**Comment by ThinaticSystem** [comment]
デプロイのこととか考えずとりあえず開発環境で使えることを優先するとすれば\
Backend側のDevcontainerコンテナにPostgresql建てちゃうでもアリかも

**Comment by marihachi** [comment]
コンテナ終了したら消えるけど、取りあえず動くみたいなこと？

**Comment by ThinaticSystem** [comment]
Postgresのdataディレクトリ (だっけ)をVolumeに永続化？かも

**Comment by marihachi** [comment]
よさそう

**Comment by marihachi** [comment]
なった
