### ISSUE TITLE
BackendとFrontendを反復横跳びできる開発環境

### ISSUE THREAD

**Issue by ThinaticSystem** [Frost-Dev/Frost#55]
## 困ってる点
現状BackendとFrontendでDevcontainerがばっさり分割されているが\
新規に機能を実装するときやFrontend側の実装中にDBをお触りしたくなってしまったときなど\
2つのVS Codeウィンドウを切り替える必要があり\
開発体験がよろしくない。

## やっていきたい
1つのVS CodeウィンドウでBackendとFrontend両方の操作 (再ビルド、DB操作等)を可能にしていきたい。

でもでも単純にがっちゃんこDevcontainerを作った場合依存関係がかなりモノリシックなコンテナが爆誕してちょっとあれなのと\
Frostリポジトリ外のサードパーティー？Frontendへ同等の開発体験を提供できないのがなんかずっこい感じがするため\
できれば第三のFrontendでも利用できるような手法にしたい。

**Comment by ThinaticSystem** [comment]
VS Codeのマルチルートワークスペースでは各フォルダごとにsettings.jsonとかを持たせることが可能\
cf. https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by ThinaticSystem** [comment]
各フロントエンドがリポジトリ内にFrostリポジトリをsubmoduleとかで持ち\
各フロントエンドで用意したDevcontainerへFrost-Backendの開発環境を差し込むような仕組みを提供できればいい感じそう

**Comment by marihachi** [comment]
FrostBackendはDevcontainer 無しのDockerfileなどを提供でいいかも

**Comment by marihachi** [comment]
モノレポやめるか

**Comment by marihachi** [comment]
モノレポやるか

**Comment by ThinaticSystem** [comment]
BackendのDockerイメージを提供する形で

**Comment by marihachi** [comment]
と思ってたけど、最終的にDevcontainer専用のDockerfileを作りました。
これはプロダクションとしては使いません。

おそらくプロダクション用としては別で
- BackendのDockerイメージ
- FrontendのDockerイメージ

をそれぞれ用意すること形になりそうです(未確定)。
