### ISSUE TITLE
(Frost-Webの)フロントエンドがREST APIをストリーミングで呼び出して結果を取得するまでの流れ

### ISSUE THREAD

**Issue by marihachi** [Frost-Dev/Frost#9]
## 登場するノードの説明
- フロントエンド(フロント): Webサーバから配布されてユーザーのブラウザ上で動作するプログラム
- Webサーバ(Web): 公式のWebアプリケーション
- APIサーバ(API): 全てのクライアントがFrostのデータを利用するためのもの

## 流れ
1. フロントがWebに向けて(ストリーミングで)restイベントを発行
2. Webのstreaming-proxyがクライアントからのrestイベントを受信
3. Webのstreaming-proxyがAPIに代理でrestイベントを発行
4. APIのstreaming-serverがrestイベントを受信
5. APIの各エンドポイントがリクエスト内容を処理
6. APIのstreaming-serverがrestイベント(レスポンス)を発行
7. Webのstreaming-proxyがAPIからのrestイベント(レスポンス)を受信
8. Webがフロントに向けてrestイベント(レスポンス)を発行

今後、変わるかもしれないけど一応

**Comment by Asteriskx** [comment]
Thx.
